spring.application.name=iot-dashboard
# Bật bảng điều khiển H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cấu hình đường dẫn DB (lưu thành file trong project để không mất khi restart)
spring.datasource.url=jdbc:h2:file:./data/iot_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update